/*
 * mqa/crc24.h -- the reflected CRC-24 used as a self-clocking scrambler
 * state in the stage-1 LSB correction step.
 *
 * The decoder keeps a 24-bit shift register and advances it one byte at a
 * time with the standard table-driven reflected CRC update. The register
 * is only ever clocked with zero input bytes, so it behaves as a Galois
 * LFSR stepping eight bits per sample; the low bits of its state select
 * the correction applied to each sample (lsb_correction.h).
 *
 * The 256-entry table the decoder ships is exactly the one generated by
 * polynomial 0x8100c9 in reflected form, so it is computed here rather
 * than embedded.
 *
 * The polynomial is not one of the catalogued CRC-24s; the register is
 * used as a Galois LFSR, here and in the renderer signalling
 * (watermark.h). See docs/prior-art.md.
 *
 * SPDX-License-Identifier: MIT
 */
#ifndef MQA_DECODE_CRC24_H
#define MQA_DECODE_CRC24_H

#include <stdint.h>

#define MQA_CRC24_POLY_REFLECTED 0x8100c9u

struct mqa_crc24 {
	uint32_t table[256];
};

void mqa_crc24_init(struct mqa_crc24 *c);

/* One reflected-CRC step: fold `byte` into `state`. */
static inline uint32_t mqa_crc24_update(const struct mqa_crc24 *c, uint32_t state, uint8_t byte)
{
	return c->table[(state ^ byte) & 0xff] ^ (state >> 8);
}

#endif
