/*
 * spec-vectors -- the test vectors of docs/mqa-stage1-spec.md appendix B.
 *
 *     build/spec-vectors DIR      write the vectors into DIR
 *     build/spec-vectors -c DIR   check this library against them
 *
 * Each vector is a text file: comment lines start with '#', everything
 * else is `name: value value ...`, decimal for signed quantities and
 * 0x-prefixed for unsigned ones. The inputs are synthetic, so the files
 * carry no audio; the stages they drive are the ones a decoder is most
 * likely to get subtly wrong.
 *
 * Provenance: every stage here reproduces the original decoder on real
 * material, so agreeing with these numbers is agreeing with that
 * decoder.
 *
 * SPDX-License-Identifier: MIT
 */
#define _POSIX_C_SOURCE 200809L
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "mqa/lcg.h"
#include "mqa/descrambler.h"
#include "mqa/entropy.h"
#include "mqa/predictor.h"
#include "mqa/reconstruct.h"
#include "mqa/recon2.h"
#include "mqa/residual_stage.h"
#include "mqa/watermark.h"

static const struct mqa_gain_params GAIN = { 203, (int32_t)0x50b59897, 7 };

static int failures;
static const char *vector_dir;     /* where the vectors live */
static int checking;               /* -c: compare instead of write */
static FILE *out;
static char cur_path[512];

/* --- emitting or checking ------------------------------------------------ */

static FILE *check_fp;
static char check_line[4096];

static void begin(const char *name, const char *title)
{
	snprintf(cur_path, sizeof cur_path, "%s/%s", vector_dir, name);
	if (checking) {
		check_fp = fopen(cur_path, "r");
		if (!check_fp) {
			printf("  %s: missing\n", cur_path);
			failures++;
		}
		return;
	}
	out = fopen(cur_path, "w");
	if (!out) {
		perror(cur_path);
		exit(1);
	}
	fprintf(out, "# %s\n# generated by tools/spec-vectors; see docs/mqa-stage1-spec.md appendix B\n",
		title);
}

static void end(void)
{
	if (check_fp) {
		fclose(check_fp);
		check_fp = NULL;
	}
	if (out) {
		fclose(out);
		out = NULL;
	}
}

/* One line: a name and `n` values, formatted by `hex`. */
static void row(const char *name, const int32_t *v, unsigned n, int hex)
{
	char buf[4000];
	unsigned i, len;

	len = (unsigned)snprintf(buf, sizeof buf, "%s:", name);
	for (i = 0; i < n && len < sizeof buf - 24; i++)
		len += (unsigned)snprintf(buf + len, sizeof buf - len,
					  hex ? " 0x%08x" : " %d", (unsigned)v[i]);
	if (!checking) {
		fprintf(out, "%s\n", buf);
		return;
	}
	if (!check_fp)
		return;
	while (fgets(check_line, sizeof check_line, check_fp)) {
		char *nl;

		if (check_line[0] == '#')
			continue;
		nl = strchr(check_line, '\n');
		if (nl)
			*nl = 0;
		if (strcmp(check_line, buf) == 0)
			return;
		printf("  %s: mismatch\n     want %s\n      got %s\n", cur_path, check_line, buf);
		failures++;
		return;
	}
	printf("  %s: ran out of lines at %s\n", cur_path, name);
	failures++;
}

static void row1(const char *name, int32_t v, int hex)
{
	row(name, &v, 1, hex);
}

/* --- the vectors --------------------------------------------------------- */

/* 1. the two generators */
static void vec_lcg(void)
{
	int32_t v[8];
	uint32_t s;
	unsigned i;

	begin("lcg.txt", "The two linear congruential generators (spec 5.1, A.5)");
	s = 0x12345678u;
	for (i = 0; i < 8; i++) {
		s = mqa_lcg_step(s);
		v[i] = (int32_t)s;
	}
	row("scrambler_from_0x12345678", v, 8, 1);
	s = 0x12345678u;
	for (i = 0; i < 8; i++) {
		s = mqa_nr_lcg_step(s);
		v[i] = (int32_t)s;
	}
	row("nr_from_0x12345678", v, 8, 1);
	row1("jump_1000_from_0x12345678", (int32_t)mqa_lcg_jump(0x12345678u, 1000), 1);
	end();
}

/* 2. the data channel's descrambler */
static void vec_descrambler(void)
{
	struct mqa_descrambler ks;
	int32_t a[16], b[16], v[32];
	uint8_t bytes[32];
	unsigned i, pos;

	begin("descrambler.txt", "Data-channel descrambling (spec 5.1)");
	for (i = 0; i < 16; i++) {
		a[i] = (int32_t)(i * 0x010203) - 0x400000;
		b[i] = (int32_t)(i * 0x030201) + 0x100000;
	}
	mqa_descrambler_init(&ks);
	pos = mqa_descrambler_fill(&ks, bytes, a, b, 0, 16);
	for (i = 0; i < 32; i++)
		v[i] = bytes[i];
	row("carrier_a", a, 16, 1);
	row("carrier_b", b, 16, 1);
	row("bytes_from_fresh_state", v, 32, 0);
	row1("ring_position_after", (int32_t)pos, 0);
	row1("lcg_a_after", (int32_t)ks.lcg[0], 1);
	row1("lcg_b_after", (int32_t)ks.lcg[1], 1);

	mqa_descrambler_start(&ks, 0x12340);
	row1("start_0x12340_lcg_a", (int32_t)ks.lcg[0], 1);
	row1("start_0x12340_lcg_b", (int32_t)ks.lcg[1], 1);
	row1("start_0x12340_budget", (int32_t)ks.budget, 0);
	row1("start_0x12340_reseeds", (int32_t)ks.reseeds, 0);
	end();
}

/* 3. the entropy decoder */
static void vec_entropy(void)
{
	static uint8_t ring_bytes[256];
	struct mqa_byte_ring ring;
	struct mqa_range_decoder rc;
	struct mqa_entropy_decoder d;
	int32_t sym[16];
	unsigned i;

	begin("entropy.txt", "The adaptive arithmetic decoder (spec 7.2, 7.5, 7.6)");
	for (i = 0; i < sizeof ring_bytes; i++)
		ring_bytes[i] = (uint8_t)(i * 37 + 11);
	memset(&ring, 0, sizeof ring);
	ring.data = ring_bytes;
	ring.size = sizeof ring_bytes;
	memset(&rc, 0, sizeof rc);
	rc.src = &ring;
	rc.base = 256;
	rc.range = 1;
	rc.value = 0;

	memset(&d, 0, sizeof d);
	d.coder = &rc;
	d.residual = &rc;
	d.rng = 0x0badc0deu;
	d.level = 0x200;
	d.level_min = 0x39;
	d.level_max = 0xe6;
	d.level_rate = 0x108f;
	d.variance = 0x10000000;
	d.gain = GAIN;
	d.scale2 = GAIN.scale;
	d.head = 4;
	for (i = 0; i < MQA_ENTROPY_TAPS; i++)
		d.decay[i] = (uint16_t)(0xf000 - 0xf00 * i - (i > 1 ? 0x10 * i : 0));
	d.decay[0] = 0xf000;
	d.decay[1] = 0xe100;
	d.decay[2] = 0xd2f0;
	d.decay[3] = 0xc5c1;

	row("ring_bytes_0_31", (int32_t[]){ ring_bytes[0], ring_bytes[1], ring_bytes[2], ring_bytes[3],
					     ring_bytes[4], ring_bytes[5], ring_bytes[6], ring_bytes[7] },
	    8, 0);
	mqa_entropy_decode(&d, sym, 16, 1);
	row("symbols", sym, 16, 0);
	row1("level_after", d.level, 0);
	row1("variance_after", d.variance, 0);
	row1("rng_after", (int32_t)d.rng, 1);
	row1("coder_range_after", (int32_t)rc.range, 1);
	row1("coder_value_after", (int32_t)rc.value, 1);
	row1("ring_cursor_after", (int32_t)ring.cursor, 0);
	{
		int32_t taps[MQA_ENTROPY_TAPS];

		for (i = 0; i < MQA_ENTROPY_TAPS; i++)
			taps[i] = d.taps[i];
		row("taps_after", taps, MQA_ENTROPY_TAPS, 0);
	}
	end();
}

/* 4. the P/Q predictor */
static void vec_predictor(void)
{
	struct mqa_predictor p;
	int32_t rec_a[16], rec_b[16], out[32];
	unsigned i;

	begin("predictor.txt", "The P/Q predictor (spec 7.7)");
	for (i = 0; i < 16; i++) {
		rec_a[i] = (int32_t)(i * 12345) - 90000;
		rec_b[i] = 70000 - (int32_t)(i * 9876);
	}
	mqa_predictor_init(&p, 0x1111u, 0x2222u, &GAIN);
	mqa_predictor_run(&p, rec_a, rec_b, out, 16);
	row("record_a", rec_a, 16, 0);
	row("record_b", rec_b, 16, 0);
	row("residuals", out, 32, 0);
	row1("y1_prev_after", p.y1_prev, 0);
	row1("y2h_prev_after", p.y2h_prev, 0);
	end();
}

/* 5. the short reconstruction filter */
static void vec_reconstruct(void)
{
	struct mqa_recon_state st;
	struct mqa_recon_coeffs k;
	int32_t l[16], r[16], carrier[2], residual[2];
	unsigned i;

	begin("reconstruct.txt", "The short reconstruction filter, variant 1 (spec 8.2)");
	mqa_recon_init(&st);
	mqa_recon_coeffs_default(&k);
	for (i = 0; i < 16; i++) {
		l[i] = (int32_t)(i * 131) - 900;
		r[i] = 700 - (int32_t)(i * 77);
	}
	{
		int32_t a[8], b[8], p[8], q[8];

		for (i = 0; i < 8; i++) {
			a[i] = (int32_t)(i * 9931) % 50000 - 25000;
			b[i] = (int32_t)(i * 7717) % 40000 - 20000;
			p[i] = (int32_t)(i * 613) % 900 - 450;
			q[i] = (int32_t)(i * 419) % 700 - 350;
		}
		row("carrier_a", a, 8, 0);
		row("carrier_b", b, 8, 0);
		row("residual_p", p, 8, 0);
		row("residual_q", q, 8, 0);
		row("dither_l", l, 16, 0);
		row("dither_r", r, 16, 0);
		for (i = 0; i < 8; i++) {
			carrier[0] = a[i];
			carrier[1] = b[i];
			residual[0] = p[i];
			residual[1] = q[i];
			mqa_recon_tap(&st, &GAIN, &k, carrier, residual, l + 2 * i, r + 2 * i);
		}
	}
	row("output_l", l, 16, 0);
	row("output_r", r, 16, 0);
	end();
}

/* 6. the alternative kernel */
static void vec_recon2(void)
{
	struct mqa_recon2_state st;
	int32_t a[16 + 24], b[16 + 24], p[24], q[24], l[48], r[48];
	unsigned i;

	begin("recon2.txt", "The alternative reconstruction kernel, variant 0 (spec 8.3)");
	for (i = 0; i < 16 + 24; i++) {
		a[i] = (int32_t)(i * 7919) % 100000 - 50000;
		b[i] = (int32_t)(i * 104729) % 90000 - 45000;
		if (i < 24) {
			p[i] = (int32_t)(i * 31337) % 3000 - 1500;
			q[i] = (int32_t)(i * 15013) % 2500 - 1250;
		}
	}
	for (i = 0; i < 48; i++) {
		l[i] = (int32_t)(i * 2711) % 700 - 350;
		r[i] = (int32_t)(i * 1949) % 500 - 250;
	}
	row("warmup_pairs_a", a, 16, 0);
	row("warmup_pairs_b", b, 16, 0);
	row("carrier_a", a + 16, 24, 0);
	row("carrier_b", b + 16, 24, 0);
	row("residual_p", p, 24, 0);
	row("residual_q", q, 24, 0);
	row("dither_l", l, 48, 0);
	row("dither_r", r, 48, 0);
	mqa_recon2_init(&st, 0);
	mqa_recon2_prime(&st, a, b, NULL, NULL, 16);
	mqa_recon2_group(&st, &GAIN, a + 16, b + 16, p, q, l, r, 24);
	row("output_l", l, 48, 0);
	row("output_r", r, 48, 0);
	end();
}

/* 7. the renderer signalling */
static void vec_watermark(void)
{
	struct mqa_watermark w;
	int32_t l[64], r[64], msg[24];
	unsigned i;

	begin("signalling.txt", "The renderer signalling (spec 11)");
	for (i = 0; i < 64; i++) {
		l[i] = (int32_t)(i * 37) - 4000;
		r[i] = 900 - (int32_t)(i * 11);
	}
	row("input_l", l, 64, 0);
	row("input_r", r, 64, 0);
	mqa_watermark_init(&w);
	mqa_watermark_set_stream(&w, 8, 10, 2, 1);
	mqa_watermark_apply(&w, l, r, 64);
	row("output_l", l, 64, 0);
	row("output_r", r, 64, 0);
	for (i = 0; i < 8; i++) {
		unsigned byte = 0, bit;

		for (bit = 0; bit < 8; bit++)
			byte = byte << 1 | (unsigned)((l[8 * i + bit] ^ r[8 * i + bit]) & 1);
		msg[i] = (int32_t)byte;
	}
	row("message_bytes", msg, 8, 0);
	end();
}

int main(int argc, char **argv)
{
	const char *dir;

	if (argc > 2 && strcmp(argv[1], "-c") == 0) {
		checking = 1;
		dir = argv[2];
	} else if (argc > 1) {
		dir = argv[1];
	} else {
		fprintf(stderr, "usage: spec-vectors DIR | spec-vectors -c DIR\n");
		return 2;
	}
	vector_dir = dir;
	vec_lcg();
	vec_descrambler();
	vec_entropy();
	vec_predictor();
	vec_reconstruct();
	vec_recon2();
	vec_watermark();
	if (checking)
		printf("spec vectors: %s\n", failures ? "MISMATCHES" : "all match");
	else
		printf("spec vectors written to %s\n", dir);
	return failures != 0;
}
